language: python
python:
- '2.7.3'
- '2.7.9'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install --upgrade pip
- pip install numpy
- pip install coveralls
- pip install -r requirements_dev.txt
- pip install .
script:
- py.test
after_success:
- coveralls